apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
    environment: test
spec:
  selector:
    matchLabels:
      app: echo
  replicas: 2
  template:
    metadata:
      labels:
        app: echo
        environment: test
    spec:
      containers:
      - name: echo
        image: kicbase/echo-server:1.0
        ports:
        - containerPort: 8080
