apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapi
  labels:
    app: movieapi
spec:
  selector:
    matchLabels:
      app: movieapi
  replicas: 5
  template:
    metadata:
      labels:
        app: movieapi
    spec:
      containers:
      - name: movieapi
        image: movieapi:2.0
        ports:
        - containerPort: 8080
        env:
          - name: DB_URL
            valueFrom: 
              configMapKeyRef:
                name: movieapi-cfg
                key: DB_URL
