apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init
data:
  01-tables.sql: |
    create table person (
      id int auto_increment,
      name varchar(150) not null,
      birthdate date null,
      constraint pk_stars primary key (id)
    );

    create table movie (
      id int auto_increment,
      title varchar(300) not null,
      year smallint not null,
      duration smallint null,
      synopsis text null,
      poster_uri varchar(300) null,
      color varchar(20) null,
      pg varchar(15) null,
      constraint pk_movie primary key (id),
      constraint uniq_movie UNIQUE(title, year),
      constraint chk_movie_year CHECK(year >= 1850)
    );

    create table have_genre(
      movie_id int not null,
      genre varchar(20) not null
    );

    alter table have_genre add constraint FK_HAVE_GENRE
      FOREIGN KEY (movie_id)
      references movie(id);
