apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmovie
  labels:
    app: dbmovie
spec:
  selector:
    matchLabels:
      app: dbmovie
  replicas: 1
  template:
    metadata:
      labels:
        app: dbmovie
    spec:
      containers:
      - name: dbmovie
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_ROOT_PASSWORD
